services:
  pulsar:
    image: apachepulsar/pulsar:2.10.3
    command: bin/pulsar standalone

# hz:
#   image: hazelcast/hazelcast:5.2.1
#   environment:
#     JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
#     CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
#   volumes:
#     - ".:/project"
#   networks:
#     - hznet
#
# mc:
#   image: hazelcast/management-center:5.2.1 
#   environment:
#     MC_DEFAULT_CLUSTER: dev
#     MC_DEFAULT_CLUSTER_MEMBERS: hz:5701
#   ports:
#     - "8080:8080"
#   networks:
#     - hznet
#
# cli:
#   image: hazelcast/hazelcast:5.2.1
#   command: hz-cli 
#   volumes:
#     - ".:/project"
#   command: >
#     tail -f < /dev/null
#   networks:
#   - hznet
#
# refdata_loader:
#   image: openjdk:11
#   command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
#   environment:
#     HZ_SERVERS: hz
#     HZ_CLUSTER_NAME: dev 
#     MACHINE_COUNT: 5
#   volumes:
#     - ".:/project"
#   networks:
#     - hznet
#
# event_generator:
#   image: openjdk:11
#   command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
#   environment:
#     HZ_SERVERS: hz
#     HZ_CLUSTER_NAME: dev 
#     MACHINE_COUNT: 5
#     RUNHOT: false
#   volumes:
#     - ".:/project"
#   networks:
#     - hznet
# 
# ui:
#   build: ./dash-image
#   command: python /project/ui/app.py 
#   ports:
#     - "8050:8050"
#   volumes:
#     - ".:/project"
#   networks:
#     - hznet


networks:
  hznet: 
  